---
production:
  cloud_name: <%= ENV['CLOUDINARY_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true

development:
  cloud_name: <%= ENV['DEV_CLOUDINARY_NAME'] %>
  api_key: <%= ENV['DEV_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['DEV_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false

test:
  cloud_name: <%= ENV['DEV_CLOUDINARY_NAME'] %>
  api_key: <%= ENV['DEV_CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['DEV_CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: false