# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen

default:
  mode: textareas

  toolbar: styleselect | undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | forecolor hilitecolor| fontsize blockquote | table | image
  plugins:
    - image
    - link
    - table
    - autoresize